let tricks = [
    "2 ball",
    "every third throw under the leg",
    "juggler's tennis",
    "reverse cascade",
    "half shower",
    "mills mess",
    "knuckle roll",
    "columns",
    "fake columns",
    "elbow pop start",
    "add stuffed animal",
    "4-2-3",
    "rainbow cross",
    "add rubick's cube",
    "add ruler (resets to cascade)",
    "every third under arm",
    "3 ball flash",
    "neck catch",
    "add quarter",
    "add ping pong ball",
    "magic swap ping-pong ball",
    "infinity",
    "reverse infinity",
    "columns overthrow variation",
    "one throw under opposite leg",
    "claw catches",
]
