#!/bin/bash

patterns=("2 ball" "every third throw under the leg" "juggler's tennis" "reverse cascade" "half shower" "mills mess" "knuckle roll" "columns" "fake columns" "elbow pop start" "add stuffed animal" "4-2-3" "rainbow cross" "add rubick's cube" "add ruler (resets to cascade)" "every third under arm" "w/ spin" "3 ball flash" "neck catch" "reset" "reset" "add quarter" "add ping pong ball" "magic swap ping-pong ball")

len=$(echo ${#patterns[*]})

declare j

case "$1" in
	"")
		offline=false ;;
	"-o"|"--offline")
		offline=true ;;
	"-l"|"--list")
		printf '%s\n' "${patterns[@]}"
		exit ;;
	*)
		echo "Invalid option."
		exit ;;
esac

geni ()
{
	if [ $offline = true ] ; then
		i=$(($RANDOM%$len))
	else
    	i=$(echo $(curl -s "https://www.random.org/integers/?num=1&min=0&max=$len&col=1&base=10&format=plain&rnd=new"))
	fi
}

score=-1

while true
do
	# do action on spacebar press
	read -s -n 1 input
	if [ "$input" = '' ] ; then
		# increment counter for last time, unless it was a reset
		if [ "${pattens[i]}" != "reset" ] ; then
		score=$((score+1))
		fi

		# get a random number, and if it is the same as the last one, get another
	    geni
	    if [ "$j" = "$i" -o "${patterns[i]}" = "" ] ; then
		geni
	    fi 
	    j="$i"

		# print out the corresponding action
	    echo ${patterns[i]}
	fi
	if [ "$input" = 'q' ] ; then
	echo ""
	echo "Score: $score"
	echo ""
	exit
	fi
done
